### ISSUE TITLE
Many false positives

### ISSUE THREAD

**Issue by carlosnewmusic** [Chax1/VRPE-Installer#27]
Should be fixed and false positives should be reported so that the antivirus does not jump.
https://www.virustotal.com/gui/file/b143a453425295a35499d0784f3eaf27439a0c6c9c3be3e1a4299acf2a26585c?nocache=1

**Comment by Chax1** [comment]
I've already been looking into false flags for the VRPE, although I would have to remove features or pieces of code to try and decrease false flags, since no anti virus tells you what specific code part triggers the avs this is a pain to find out and resolve.

Another notable fact is that by behavior, installers like this ARE malware, they download an exe and then install it, sure its not intended to harm, and wont harm, but by definition and by how it works, it is malware, most companies usually resolve the av issues by codesigning their installers, which would cost me 300$ a year, and I do not have that kind of money.
