### ISSUE TITLE
"--------------------------- Error during runtime! --------------------------- Exception Message: The configuration section 'connectionStrings' has an unexpected declaration. "

### ISSUE THREAD

**Issue by Coder1062** [Chax1/VRPE-Installer#30]
I tried installing the VRP essentials but got this when I opened it, **Help!**

**Comment by Chax1** [comment]
Hey there, please try deleting the VRP folder inside of %localappdata%You can get to that directory by searching exactly that inside of Windows. Gesendet von Mail für Windows Von: Coder1062Gesendet: Sonntag, 6. August 2023 18:15An: Chax1/VRPE-InstallerCc: SubscribedBetreff: [Chax1/VRPE-Installer] "--------------------------- Error during runtime! --------------------------- Exception Message: The configuration section 'connectionStrings' has an unexpected declaration. " (Issue #30) I tried installing the VRP essentials but got this when I opened it, Help!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by frxctura** [comment]
Hey there, please try deleting the VRP folder inside of %localappdata%
You can get to that directory by searching exactly that inside of Windows.

**Comment by frxctura** [comment]
Afterwards try starting the VRPE again

**Comment by Coder1062** [comment]
there is no folder called VRP

**Comment by frxctura** [comment]
I heavily assume your Windows Installation is broken due to this being an issue with the Configuration Manager, there are no issues with the program on my end and I cannot reproduce this problem, reinstall Windows.

**Comment by frxctura** [comment]
Alternatively, try repairing from the inside via an administrative command prompt and run the following commands.

sfc /scannow
and after
Dism.exe /Online /Cleanup-Image /RestoreHealth
Dism.exe /online /Cleanup-Image /StartComponentCleanup.
